### ISSUE TITLE
Documentation Request:  How do I run the tests?

### ISSUE THREAD

**Issue by billdenney** [pharmetheus/PsNplus#1]
Hello,

Thanks for writing PsNplus!

Can you please document the preferred way of running the PsNplus tests?  Looking at the code, I'd guess:

```
cd /location/of/perl/test
prove -r unit
prove -r system
```

Is that correct, and if so, can you please add it to the README.md so that I can have a source to document that I'm testing the right way?

**Comment by kharling** [comment]
Yes it is correct. Thank you for making it so extremely easy for me to add the documentation. Done.

**Comment by billdenney** [comment]
Thanks!
